//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCatalogDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarCatalogEntities : DbContext
    {
        public CarCatalogEntities()
            : base("name=CarCatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyTypeDB> BodyType { get; set; }
        public virtual DbSet<CarDB> Car { get; set; }
        public virtual DbSet<GearBoxTypeDB> GearBoxType { get; set; }
        public virtual DbSet<ManufacturerDB> Manufacturer { get; set; }
        public virtual DbSet<WheelDriveTypeDB> WheelDriveType { get; set; }
    }
}
