//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCatalogDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDB
    {
        public int ID { get; set; }
        public Nullable<int> BodyTypeID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> GearBoxTypeID { get; set; }
        public Nullable<int> WheelDriveTypeID { get; set; }
        public string Model { get; set; }
        public string Image { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual BodyTypeDB BodyType { get; set; }
        public virtual GearBoxTypeDB GearBoxType { get; set; }
        public virtual ManufacturerDB Manufacturer { get; set; }
        public virtual WheelDriveTypeDB WheelDriveType { get; set; }
    }
}
